// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBffKhcX8fgamYxTC2mwjZ9A42kQgQnGe8',
    appId: '1:1036361536030:web:842825194b9a45c2b0d40f',
    messagingSenderId: '1036361536030',
    projectId: 'fair-app-test',
    authDomain: 'fair-app-test.firebaseapp.com',
    storageBucket: 'fair-app-test.appspot.com',
    measurementId: 'G-Z0XT4F3KFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq5x149lh_5SYmXaskF2Eolk6930FWjV4',
    appId: '1:1036361536030:android:ed4c2cecbf2ba415b0d40f',
    messagingSenderId: '1036361536030',
    projectId: 'fair-app-test',
    storageBucket: 'fair-app-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRgcl75snAN-DqdmwkVbMypoSrORIAPgA',
    appId: '1:1036361536030:ios:16ea76850c6d54d5b0d40f',
    messagingSenderId: '1036361536030',
    projectId: 'fair-app-test',
    storageBucket: 'fair-app-test.appspot.com',
    iosClientId: '1036361536030-lmmu0a3krub81nlhj1tcsvofu66con26.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutorial1EcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRgcl75snAN-DqdmwkVbMypoSrORIAPgA',
    appId: '1:1036361536030:ios:16ea76850c6d54d5b0d40f',
    messagingSenderId: '1036361536030',
    projectId: 'fair-app-test',
    storageBucket: 'fair-app-test.appspot.com',
    iosClientId: '1036361536030-lmmu0a3krub81nlhj1tcsvofu66con26.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTutorial1EcommerceApp',
  );
}
